name: spritewidget
description: SpriteWidget is an open source toolkit for building complex, high performance animations and 2D games with Flutter.
version: 0.9.22
author: Viktor Lidholt <viktorlidholt@gmail.com>
homepage: https://spritewidget.com/
repository: https://github.com/spritewidget/spritewidget/
issue_tracker: https://github.com/spritewidget/spritewidget/issues
environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.7.8 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
