name: fitness
publish_to: 'none'
description: A new Flutter project.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  spritewidget:
    path: ../../

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/jumpingjack.json
    - assets/jumpingjack.png